package pro.liliya.core.logging

object LogConfig {

    const val SYSTEM_START = "SYSTEM_START"
    const val SYSTEM_STOP = "SYSTEM_STOP"

    const val MODULE_INIT = "MODULE_INIT"
    const val MODULE_READY = "MODULE_READY"

    const val MODULE_DEPENDENCY_CHECK = "MODULE_DEPENDENCY_CHECK"
    const val MODULE_DEPENDENCY_RESOLVED = "MODULE_DEPENDENCY_RESOLVED"
    const val MODULE_DEPENDENCY_FAILED = "MODULE_DEPENDENCY_FAILED"
    const val MODULE_DEPENDENCY_CYCLE = "MODULE_DEPENDENCY_CYCLE"
    const val MODULE_START_ORDER = "MODULE_START_ORDER"

    const val FILE_CREATE = "FILE_CREATE"
    const val FILE_WRITE = "FILE_WRITE"

    const val MODEL_LOAD_BEGIN = "MODEL_LOAD_BEGIN"
    const val MODEL_LOAD_END = "MODEL_LOAD_END"

    const val ERROR_CAUGHT = "ERROR_CAUGHT"

    const val UNKNOWN = "UNKNOWN"
}
